stages:
  data_preparation:
    cmd: python src/data/data_processor.py
    deps:
    - src/data/data_processor.py
    outs:
    - models/scaler.joblib
    
  train_models:
    cmd: python src/models/train.py
    deps:
    - src/models/train.py
    - src/data/data_processor.py
    - models/scaler.joblib
    params:
    - random_state
    - test_size
    metrics:
    - metrics.json:
        cache: false
    outs:
    - models/
    - mlruns/

  evaluate_models:
    cmd: python src/models/evaluate.py
    deps:
    - src/models/evaluate.py
    - models/
    metrics:
    - evaluation_metrics.json:
        cache: false

plots:
- plots/confusion_matrix.png
- plots/feature_importance.png
- plots/predictions_vs_actual.png
