random_state: 42
test_size: 0.2

model_params:
  linear_regression: {}
  
  random_forest:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  
  gradient_boosting:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    random_state: 42

training:
  experiment_name: california_housing_prediction
  mlflow_tracking_uri: sqlite:///mlflow.db

api:
  host: 0.0.0.0
  port: 8000
